# Generated by Django 5.2.17 on 2026-09-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='book_quantity_non_negative'),
        ),
    ]
